//
//  GreetingRouter.swift
//  Patterns
//
//  Created by Dmitriy Akhmerov on 09.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GreetingRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol GreetingDataPassing {
    var dataStore: GreetingDataStore? { get }
}

class GreetingRouter: NSObject, GreetingRoutingLogic, GreetingDataPassing {
    weak var viewController: GreetingViewController?
    var dataStore: GreetingDataStore?

// MARK: Routing (navigating to other screens)

//func routeToSomewhere(segue: UIStoryboardSegue?) {
//    if let segue = segue {
//        let destinationVC = segue.destination as! SomewhereViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//        let storyboard = UIStoryboard(name: "Main", bundle: nil)
//        let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
//}

// MARK: Navigation to other screen

//func navigateToSomewhere(source: GreetingViewController, destination: SomewhereViewController) {
//    source.show(destination, sender: nil)
//}

// MARK: Passing data to other screen

//    func passDataToSomewhere(source: GreetingDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
