//
//  GreetingConfigurator.swift
//  Patterns
//
//  Created by Dmitriy Akhmerov on 09.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GreetingConfigurator {

	static let shared = GreetingConfigurator()

	private init() {}

	func configure(with viewController: GreetingViewController) {
		let viewController = viewController
		let interactor = GreetingInteractor()
		let presenter = GreetingPresenter()
		let router = GreetingRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
    }
}
