//
//  GreetingViewController.swift
//  Patterns
//
//  Created by Dmitriy Akhmerov on 09.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GreetingDisplayLogic: AnyObject {
    func displayGreeting(viewModel: GreetingViewModel)
}

class GreetingViewController: UIViewController, GreetingDisplayLogic {

	// MARK: UI Elements

	let greetingLabel: UILabel = {
		let label = UILabel()
		label.backgroundColor = .white
		label.textColor = .black
		label.translatesAutoresizingMaskIntoConstraints = false
		label.textAlignment = .center
		label.numberOfLines = 0
		return label
	}()

    var interactor: GreetingBusinessLogic?
    var router: (NSObjectProtocol & GreetingRoutingLogic & GreetingDataPassing)?

	// MARK: - Приватный метод установки UI

	private func setupUI() {
		view.addSubview(greetingLabel)
		NSLayoutConstraint.activate([
			greetingLabel.topAnchor.constraint(equalTo: view.topAnchor),
			greetingLabel.bottomAnchor.constraint(equalTo: view.bottomAnchor),
			greetingLabel.leftAnchor.constraint(equalTo: view.leftAnchor),
			greetingLabel.rightAnchor.constraint(equalTo: view.rightAnchor),
		])
	}

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
		GreetingConfigurator.shared.configure(with: self)
    }

	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
		setupUI()
		showGreeting()
	}
    
    // MARK: - request data from GreetingInteractor

    func showGreeting() {
        let request = GreetingRequest()
        interactor?.showGreeting(request: request)
    }

    // MARK: - display view model from GreetingPresenter

    func displayGreeting(viewModel: GreetingViewModel) {
		greetingLabel.text = viewModel.greeting
    }
}
